title: "Pankaj Badatia Portfolio"
description: "Showcasing my journey and blogs."
baseurl: "/pankajbadatia.github.io"
url: "https://example.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /blog/:year/:month/:title/
