title: "My Portfolio and Blog"
description: "Welcome to my personal portfolio and blog!"
baseurl: "" # Replace with base URL if hosted in a subdirectory
url: "https://example.com" # Replace with your domain
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
