
title: "Pankaj Badatia"
description: "Data Scientist | AI Advisor | Developer"
url: "https://pankajbadatia.github.io"
author:
  name: "Pankaj Badatia"
  bio: "Passionate about AI, Machine Learning, and driving innovation through technology."
