title: "Pankaj Badatia Portfolio"
description: "Showcasing my journey and sharing my blogs."
baseurl: "pankajbadatia.github.io"
url: "https://example.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
